name: windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  msys2-clang64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: CLANG64
          update: true
          install: mingw-w64-clang-x86_64-toolchain mingw-w64-clang-x86_64-cmake mingw-w64-clang-x86_64-ninja base-devel git

      - name: INSTALL MSVC
        run: |
          wget https://aka.ms/vs/17/release/vs_BuildTools.exe
          ./vs_BuildTools.exe --quiet --wait --norestart --nocache \
          --installPath "D:\Program Files\Microsoft Visual Studio\2022" \
          --add "Microsoft.VisualStudio.Component.Roslyn.Compiler" \
          --add "Microsoft.Component.MSBuild" \
          --add "Microsoft.VisualStudio.Component.CoreBuildTools" \
          --add "Microsoft.VisualStudio.Workload.MSBuildTools" \
          --add "Microsoft.VisualStudio.Component.VC.Tools.x86.x64" \
          --add "Microsoft.VisualStudio.Component.Windows10SDK.19041"

      - name: BUILD SFML3
        run: |
          git clone --branch 3.0.1 --depth 1 https://github.com/SFML/SFML.git
          cd SFML
          cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/clang64 -DSFML_USE_STATIC_STD_LIBS=ON
          cmake --build build --config Release
          cmake --build build --config Release --target install
          rm -rf build/
          cmake -B build -G "Visual Studio 17 2022" -DCMAKE_INSTALL_PREFIX=../SFML-3.0.1 -DSFML_USE_STATIC_STD_LIBS=ON
          cmake --build build --config Release -j$(nproc)
          cmake --build build --config Release --target install

      - name: BUILD HENTAI-MSVC
        run: |
          cmake -B build -G "Visual Studio 17 2022" -DCMAKE_PREFIX_PATH="SFML-3.0.1/"
          cmake --build build --config Release -j$(nproc)

      - name: Run HENTAI-MSVC
        run: |
          timeout 5 ./hentai
          rm -rf build/

      - name: BUILD HENTAI-CLANG64-Cmake-Ninja
        run: |
          cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release

      - name: Run HENTAI-CLANG64-Cmake-Ninja
        run: |
          timeout 5 ./hentai

      - name: BUILD HENTAI-Makefile
        run: |
          make release -j$(nproc)

      - name: Run HENTAI-Makefile
        run: |
          timeout 5 ./release/hentai
          make clean

      - name: BUILD HENTAI-Makefile-0721
        run: |
          make -f Makefile-0721 release -j$(nproc)

      - name: Run HENTAI-Makefile-0721
        run: |
          timeout 5 ./release/hentai